config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end

  resources :comments

  get "/about" => "home#about"

  root 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :comments

  validates :title, presence:   {message: "Must have a title!"},
                    uniqueness: {message: "Title already exists database!"},
                    length:     {minimum: 1}
  validates :body, presence:    {message: "Can't be empty!"},
                    uniqueness: {message: "Title already exists database!"},
                    length:     {minimum: 1}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index

  end

  def create
    @comment = Comment.new
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @posts = Post.all
  end


  def new
    @post = Post.new
  end

  def show

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find params[:id]
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]

    if @post.update post_params
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find params[:id] 
    @post.destroy
    redirect_to posts_path
  end


private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@post, Comment.new]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/home/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/home/_nav.html.erb
<%= link_to "Home", root_path %> |
<%= link_to "About", about_path %> |
<%= link_to "New Post", new_post_path %> |
<%= link_to "Post Archive", posts_path %> |

app/views/home/about.html.erb
<h1>The Potential..</h1>

<img src="/assets/DNA.jpg" alt="" />

app/views/home/index.html.erb
<h1>My Blog:<br><br>

 <img src="http://i.imgur.com/f1VmuOQ.jpg" alt="img" align="middle" />
  <br><br>The Beginnings of the Gover <i>net</i>...</h1>
<br><br><br>




<p>

  <% @posts.each do |post| %>
  <%= link_to post.title, post_path(post) %>
  <div class="posts" order="Desc">
  <%= post.body %>
  </div>
</p>
<% end %>






<%= render '/comments/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<%= render 'nav' %>


<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= @post.errors.full_messages.join(", ") %>

<strong>
<%= form_for @post do |f| %>
<p><%= f.label(:title) %></p>
<p><%= f.text_field(:title) %></p>
<p><%= f.label(:body) %></p>
<p><%= f.text_area(:body) %></p>
<p><%= f.submit %></p>
</strong>
<% end %>

<h2>Add a comment: </h2>

<%= form_for @post do |f| %>

<p>
  <%= f.label :body %> <br>
  <%= f.text_field :body %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/_nav.html.erb
<%= link_to "Home", root_path %> |
<%= link_to "About", about_path %> |
<%= link_to "New Post", new_post_path %> |
<%= link_to "Post Archive", posts_path %> |

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Posts Index</h1>

<table>
  <tr>
    <th>Title:</th>
    <th>Post:</th>
    <th><colspan="2"></th>
  </tr>

  <% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.body %></td>
    <td><%= link_to 'Show', post_path(post) %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post_path(post),
            method: :delete,
            data: { confirm: 'Are you sure?' } %></td>
  </tr>

<% end %>
</table>

<p>
  <%= link_to "Back", new_post_path %>
</p>

app/views/posts/new.html.erb
<img src="/assets/billhicksshirt.jpg" align="right" />
<h1>New Post</h1>


<%= render "form" %>

app/views/posts/show.html.erb
<h1>
  <strong>Title: </strong>
  <%= @post.title %>
</h1>


<p>
  <strong>Body: </strong>
  <%= @post.body %>
</p>
<br>

<p>
  <%= link_to "Back", new_post_path %>
</p>

<p>
  <%= link_to "Post Archive", posts_path %>
</p>

<p><%= link_to 'Destroy', post_path(@post),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></p>